import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:kino24/other/app_export.dart';

//для цвета и тем
class ThemeHelper {
  //текущая тема
  var _appTheme = PrefUtils().getThemeData();

// карта цветов
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// карта цветовых схем
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  //возврат основных тем
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //возврат темы из карты

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  //возврат текцщих данных темы
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //возврат темы из карты

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(5.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.white.withOpacity(0.9),
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(15.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray4F4F4F,
      ),
    );
  }

  //возврат основных цветов темы
  PrimaryColors themeColor() => _getThemeColors();

  // возврат текущих данных темы
  ThemeData themeData() => _getThemeData();
}

//темы текста (стили)
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
    headlineLarge: TextStyle(
      color: appTheme.white,
      fontSize: 30.fSize,
      fontFamily: 'Open Sans',
      fontWeight: FontWeight.w700,
    ),
    titleMedium: TextStyle(
      color: appTheme.white,
      fontSize: 18.fSize,
      fontFamily: 'Open Sans',
      fontWeight: FontWeight.w600,
    ),
      //   bodyLarge: TextStyle(
      //     color: appTheme.white,
      //     fontSize: 16.fSize,
      //     fontFamily: 'Open Sans',
      //     fontWeight: FontWeight.w400,
      //   ),
        bodyMedium: TextStyle(
          color: appTheme.white,
          fontSize: 14.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
      //   bodySmall: TextStyle(
      //     color: appTheme.blueGray900,
      //     fontSize: 12.fSize,
      //     fontFamily: 'Open Sans',
      //     fontWeight: FontWeight.w400,
      //   ),
      //   headlineSmall: TextStyle(
      //     color: appTheme.white,
      //     fontSize: 24.fSize,
      //     fontFamily: 'Open Sans',
      //     fontWeight: FontWeight.w600,
      //   ),
      //   labelLarge: TextStyle(
      //     color: appTheme.white.withOpacity(0.67),
      //     fontSize: 12.fSize,
      //     fontFamily: 'Open Sans',
      //     fontWeight: FontWeight.w600,
      //   ),
      //   titleLarge: TextStyle(
      //     color: appTheme.white,
      //     fontSize: 20.fSize,
      //     fontFamily: 'Open Sans',
      //     fontWeight: FontWeight.w600,
      //   ),
      //   titleSmall: TextStyle(
      //     color: appTheme.gray4F4F4F,
      //     fontSize: 14.fSize,
      //     fontFamily: 'Open Sans',
      //     fontWeight: FontWeight.w600,
      //   ),
      );
}

//цветовые схемы
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Основные цвета

    //Оранжевый FF5733
    primary: Color(0XFFFF5733),

    primaryContainer: Color(0XFF1E1E1E),
    secondary: Color(0XFF1E1E1E),
    secondaryContainer: Color(0XFFFF5733),
    tertiary: Color(0XFF1E1E1E),
    tertiaryContainer: Color(0XFFFF5733),

    // Background
    background: Color(0XFF121212),

    // Surface colors
    surface: Color(0XFF1E1E1E),
    surfaceTint: Color(0XCC121212),
    surfaceVariant: Color(0XFFFF5733),

    // Error colors
    error: Color(0XCC121212),
    errorContainer: Color(0XFFFF1D45),
    onError: Color(0XFF7C7C7C),
    onErrorContainer: Color(0XCC121212),

    // On colors(text colors)
    onBackground: Color(0XFFBCBCBC),
    onInverseSurface: Color(0XFF7C7C7C),
    onPrimary: Color(0XCC121212),
    onPrimaryContainer: Color(0XFFBCBCBC),
    onSecondary: Color(0XFFBCBCBC),
    onSecondaryContainer: Color(0XCC121212),
    onTertiary: Color(0XFFBCBCBC),
    onTertiaryContainer: Color(0XCC121212),

    // Other colors
    outline: Color(0XCC121212),
    outlineVariant: Color(0XFF1E1E1E),
    scrim: Color(0XFF1E1E1E),
    shadow: Color(0XCC121212),

    // Inverse colors
    inversePrimary: Color(0XFF1E1E1E),
    inverseSurface: Color(0XCC121212),

    // Pending colors
    onSurface: Color(0XFFBCBCBC),
    onSurfaceVariant: Color(0XCC121212),
  );
}

// все цвета
class PrimaryColors {
  // Black
  Color get black => Color(0XFF000000);
  Color get blackBack => Color(0XFF121212);

  // White
  Color get white => Color(0XFFFFFFFF);

  // Blue b Orange прозрачность ~20
  Color get blueP20 => Color(0X333498DB);
  Color get orangeP20 => Color(0X33FF5733);

  Color get whiteP70 => Color(0XB3FFFFFF);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray900 => Color(0XFF263238);

  // DeepOrange
  //Color get deepOrange600 => Color(0XFFF24E1E);

  // Gray
  Color get gray100 => Color(0XFFF5F5F5);
  Color get gray10006 => Color(0X06F7F7F7);
  Color get gray200 => Color(0XFFEEEEEE);
  Color get gray700 => Color(0XFF626262);
  Color get gray4F4F4F => Color(0XFF4F4F4F);

  // LightGreenCc
  Color get lightGreen800Cc => Color(0XCC48A21E);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
