name: kino24
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.0
  flutter_svg_provider: ^1.0.3
  cached_network_image: ^3.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  connectivity_plus: ^5.0.1
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^1.10.3
  flutter_native_splash: ^2.3.4
  page_view_indicators: ^2.0.0
  bloc_concurrency: ^0.2.0
  go_router: ^6.0.1
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  dio: ^4.0.6
  sizer: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  google_sign_in: ^6.1.5
  url_launcher: ^6.2.1
  flutter_inappwebview: ^5.8.0
  youtube_player_flutter: ^8.0.0

  cupertino_icons: ^1.0.2

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSansRomanLight.ttf
          weight: 300
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanBold.ttf
          weight: 700
